
maven_jar(
    name = "junit",
    artifact = "junit:junit:4.11",
)

bind(
  name = "junit_jar",
  actual = "@junit//jar"
)

maven_jar(
    name = "hamcrest_all",
    artifact = "org.hamcrest:hamcrest-all:1.3",
)

bind(
  name = "hamcrest_all_jar",
  actual = "@hamcrest-all//jar"
)
